# Site settings
title: carmen chui
email: cchui@mie.utoronto.ca
description: carmen chui
baseurl: 

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/carmenchui
  - title: github
    url: http://github.com/carmenchui
  - title: linkedin
    url: http://linkedin.com/in/carmenchui
# Postal address (add as many lines as necessary)
address:
  - line: Toronto, ON, Canada

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'
  
# Build settings
markdown: kramdown
permalink: pretty
