# Dependencies
markdown:         kramdown
highlighter:      rouge
remote_theme: fongandrew/hydeout

# Setup
locale                   : "en-US" 
title:            Carmen Chui
tagline:          'Carmen Chui'
description:      'postdoctoral fellow'
url:              https://carmenchui.github.io
baseurl:          '/'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name             : "Carmen S. Chui"
  avatar           : "stl.jpg"
  bio              : "Postdoctoral Fellow at the University of Toronto"
  location         : "Toronto, ON"
  employer         : 
  googlescholar    : "https://scholar.google.ca/citations?user=R1gxO74AAAAJ&hl=en"
  dblp    : "http://dblp.uni-trier.de/pers/hd/c/Chui:Carmen"
  email            : 
  uri              : 
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         : 
  foursquare       :
  github           : "carmenchui"
  google_plus      :
  keybase          :
  instagram        : 
  lastfm           :
  linkedin         : "carmenchui"
  orcid            : "http://orcid.org/0000-0001-9493-5912"
  pinterest        :
  soundcloud       :
  stackoverflow    : # http://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  twitter          : 
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        : 


paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
