# Dependencies
markdown:         kramdown
highlighter:      rouge
remote_theme: fongandrew/hydeout

# Setup
locale                   : "en-US" 
title:            Carmen Chui
tagline:          'Carmen Chui'
description:      'postdoctoral fellow'
url:              https://carmenchui.github.io
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name             : "Carmen S. Chui"
  avatar           : "stl.jpg"
  bio              : "Postdoctoral Fellow at the University of Toronto"
  location         : "Toronto, ON"
  employer         : 
  googlescholar    : "https://scholar.google.ca/citations?user=R1gxO74AAAAJ&hl=en"
  dblp    : "http://dblp.uni-trier.de/pers/hd/c/Chui:Carmen"
  email            : "cchui[at]mie[dot]utoronto[dot]ca"
  uri              : 
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         : 
  foursquare       :
  github           : "https://github.com/carmenchui"
  google_plus      :
  keybase          :
  instagram        : 
  lastfm           :
  linkedin         : "https://linkedin.com/in/carmenchui"
  orcid            : "http://orcid.org/0000-0001-9493-5912"
  pinterest        :
  soundcloud       :
  stackoverflow    : # http://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  twitter          : 
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        : 

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  service:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  most:
    output: true
    permalink: /:collection/:path/


# Defaults
defaults:
  # _posts
#  - scope:
#      path: ""
#      type: posts
#    values:
#      layout: single
#      author_profile: true
#      read_time: true
#      comments: true
#      share: true
#      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _service
  - scope:
      path: ""
      type: service
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _most
  - scope:
      path: ""
      type: most
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
# _portfolio
#  - scope:
#      path: ""
#      type: portfolio
#    values:
#      layout: single
#      author_profile: true
#      share: true
#      comment: true
  # _talks
#  - scope:
#      path: ""
#      type: talks
#    values:
#      layout: talk
#      author_profile: true
#      share: true


# Outputting
permalink: /:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: America/Toronto # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

#paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
