# Site settings
title: carmen chui
email: cchui@mie.utoronto.ca
description: carmen chui
baseurl: 

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 000000
  secondary: ffffff
  secondary-dark: 333333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/carmenchui
  - title: github
    url: http://github.com/carmenchui
  - title: linkedin
    url: http://linkedin.com/in/carmenchui
# Postal address (add as many lines as necessary)
address:
  - line: Toronto, ON, Canada

# Build settings
markdown: kramdown
permalink: pretty
